import type { GeneratorPlugin } from '@open-mercato/shared/modules/generators'

function buildOutput({ importSection, entriesLiteral }: { importSection: string; entriesLiteral: string }): string {
  return `// AUTO-GENERATED by mercato generate registry
import type { TemplateRegistryEntry } from '@open-mercato/pdf-generators/modules/pdf_generators/lib/interfaces'
${importSection ? `\n${importSection}\n` : ''}
export const pdfGeneratorTemplateEntries: Array<{ moduleId: string; templates: TemplateRegistryEntry[] }> = [
${entriesLiteral ? `  ${entriesLiteral}\n` : ''}]
`
}

const pdfGeneratorsPlugin: GeneratorPlugin = {
  id: 'pdf-generators.templates',
  conventionFile: 'pdf-generators.ts',
  importPrefix: 'PDF_GENERATORS_TEMPLATES',
  configExpr: (importName: string, moduleId: string) =>
    `{ moduleId: '${moduleId}', templates: ((${importName}.default ?? ${importName}.templates ?? []) as TemplateRegistryEntry[]) }`,
  outputFileName: 'pdf-generators.generated.ts',
  buildOutput,
  bootstrapRegistration: {
    entriesExportName: 'pdfGeneratorTemplateEntries',
    registrationImports: [
      `import { templateRegistry } from '@open-mercato/pdf-generators/modules/pdf_generators/lib/template-registry'`,
    ],
    buildCall: (name: string) =>
      `templateRegistry.registerExternal(${name}.flatMap((e) => e.templates))`,
  },
}

export const generatorPlugins: GeneratorPlugin[] = [pdfGeneratorsPlugin]

export default generatorPlugins
